### ISSUE TITLE
Destiny and Destination

### ISSUE THREAD

**Issue by louisguitton** [grmaciel/nodejs-flight-scrapper#13]
Hey man, I had a read through: cool stuff!
That pupeeter library seems really handy

I could help but notice a fun misuse of the word `destiny` instead of `destination`
![image](https://user-images.githubusercontent.com/7823843/61579405-d1d31000-ab04-11e9-84ce-78d63e98f10f.png)
vs
![image](https://user-images.githubusercontent.com/7823843/61579410-f0d1a200-ab04-11e9-86d3-081be908acf0.png)

Sorry for the troll :P

**Comment by grmaciel** [comment]
Good catch, didn't realise that. Will create a PR and tag you :D

**Comment by grmaciel** [comment]
Fixed to please you @louisguitton

**Comment by louisguitton** [comment]
aha @grmaciel really nice !
